name: site
version: 0.1.0.0
category: Web
author: Jason Shipman
maintainer: jasonpshipman@gmail.com
copyright: 2017-2020 (C) Jason Shipman
license: BSD3
homepage: https://github.com/jship/stub#readme
extra-source-files:
- README.md
dependencies:
- base
- filepath
- hakyll
executables:
  site:
    main: site.hs
    ghc-options: -threaded
